CREATE USER oldman IDENTIFIED BY 1234;
ALTER USER oldman DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER TO oldman WITH ADMIN OPTION;

COMMIT;
